---
# vim: ts=2 sw=2 ai expandtab

- name: Information for Instances
  hosts: rhel
  connection: smart
  gather_facts: true
  tasks:
    - debug:
        msg: "{{ inventory_hostname }} - {{ ansible_host }}"
